apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: delta-python
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: testacr321.azurecr.io/delta:v1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/bitnami/spark/examples/src/main/python/delta.py
  sparkVersion: 3.5.0
  driver:
    labels:
      version: 3.5.0
    cores: 1
    coreLimit: 1200m
    memory: 512m
    serviceAccount: spark
  executor:
    labels:
      version: 3.5.0
    instances: 1
    cores: 1
    coreLimit: 1200m
    memory: 512m
